@startuml "Система - классы"
left to right direction
class система{
    +Часы: datetime
    +Считать рабочее время()
    +Присвоить задачу подчиненому()
    +Отслеживать прогресс выполнения задачи()
}
class подчиненый{
    +ФИО: string
    +ID: integer
    +Выполнить задачу()
    +Вести учет рабочего времени()
}
class начальник{
    +ФИО: string
    +Выдать задачу для выполнения()
    +Следить за прогрессом выполнения задач()
}
начальник -- система: Выдает задачи, следит за их выполнением >
система -- подчиненый: Выдает задачи, отслеживает прогресс выполнения задачи >
подчиненый -- система: Учитывает рабочее время >
@enduml