@startuml "Система - диаграмма"
left to right direction
skinparam packageStyle rect
actor подчиненый
actor начальник
rectangle Система {
начальник --> (назначение задачи)
(назначение задачи) --> подчиненый
начальник --> (отслеживание выполнения задачи)
(отслеживание выполнения задачи) --> подчиненый
подчиненый --> (учет времени)
}
@enduml