@startuml "Система - последовательность"

participant Начальник
participant Система
participant Работник

Начальник -> Система: 1. Постановка задачи
Система -> Работник: 2. Оповещение о новой задаче
Работник -> Работник: 3. Выполнение задачи
Работник -> Система: 4. Отчет о выполненой задаче
Начальник -> Система: 5. Контроль рабоче времени

@enduml