@startuml Диаграмма развёртывания
top to bottom direction
node Начальник{
        artifact Наблюдатель
        }

node Сотрудник{
       artifact Исполнитель
       }

node Система{
node Учет задач {
artifact Информация о выполнении задач
artifact Информация о назначении задач
}
node Часы {
    artifact Учет рабочего времени
}
}
Начальник --0 Система взаимодействие
Сотрудник --0 Система взаимодействие
@enduml